apiVersion: v1
kind: Service
metadata:
  name: red-green-service
  namespace: traffic-shifting
  labels:
    app: red-green-deployment
spec:
  type: LoadBalancer
  selector: 
    app: red-green-deployment
  ports:
  - name: green
    protocol: TCP
    port: 8888
    targetPort: 5678